[package]
name = "convert_case"
version = "0.3.2"
authors = ["David Purdum <purdum41@gmail.com>"]
edition = "2018"
description = "Convert strings into any case"
license = "MIT"
keywords = [ "casing", "case", "string" ]
categories = [ "text-processing" ]
readme = "README.md"
repository = "https://github.com/rutrum/convert-case"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
strum = "0.18.0"
strum_macros = "0.18.0"
